# Generated by Django 5.2.9 on 2026-01-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='accomplishments',
            field=models.TextField(blank=True, help_text='Key accomplishments and learnings'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='architecture',
            field=models.TextField(blank=True, help_text='Technical architecture details (one per line or bullet points)'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='features',
            field=models.TextField(blank=True, help_text='Project features (one per line or bullet points)'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='final_consideration',
            field=models.TextField(blank=True, help_text='Final thoughts and reflections'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='purpose',
            field=models.TextField(blank=True, help_text='Purpose and context of the project'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='technical_challenges',
            field=models.TextField(blank=True, help_text='Technical challenges and solutions (one per line or bullet points)'),
        ),
    ]
