# Generated by Django 5.2.9 on 2026-01-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_casestudy_accomplishments_casestudy_architecture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='client',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='project_date',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='case_studies/'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='accomplishments',
            field=models.TextField(blank=True, help_text='Key accomplishments and outcomes', null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='architecture',
            field=models.TextField(blank=True, help_text='System architecture details (one per line)', null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='features',
            field=models.TextField(blank=True, help_text='Key features (one per line)', null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='final_consideration',
            field=models.TextField(blank=True, help_text='Final thoughts and lessons learned', null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='live_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='purpose',
            field=models.TextField(blank=True, help_text='Project purpose and objectives', null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='short_description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='technical_challenges',
            field=models.TextField(blank=True, help_text='Technical challenges faced (one per line)', null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
